# Canonical Syllabus Data matching uploaded DU DSE-3 Digital Image Processing syllabus

UNITS_INFO = {
    'unit-1': {
        'id': 'unit-1',
        'num': 'Unit I',
        'title': 'Introduction to Digital Image Processing',
        'color': '#0284C7',
        'color_dark': '#38BDF8',
        'syllabus_line': 'Introduction to Digital Image Processing: Fundamentals of Image Processing, Image Formation, Sampling, and Quantization, Types of Images: Grayscale, RGB, Multispectral, Image Representation: Pixels, Bit Depth, and Resolution, Color Models: RGB, HSV, CMY, YUV, File Formats: BMP, JPEG, PNG, TIFF.',
        'chapters_syllabus_order': ['ch01', 'ch02', 'ch03', 'ch04', 'ch05']
    },
    'unit-2': {
        'id': 'unit-2',
        'num': 'Unit II',
        'title': 'Image Enhancement and Restoration',
        'color': '#0D9488',
        'color_dark': '#2DD4BF',
        'syllabus_line': 'Image Enhancement and Restoration: Spatial Domain Techniques, Histogram Equalization, Spatial Filtering: Smoothing, Sharpening, Edge Detection, Frequency Domain Techniques, Fourier Transform and Its Applications, Frequency Filters: Low-Pass, High-Pass, Band-Pass, Noise Reduction and Image Restoration Techniques.',
        'chapters_syllabus_order': ['ch06', 'ch07', 'ch08', 'ch09', 'ch10', 'ch11', 'ch12', 'ch13', 'ch14']
    },
    'unit-3': {
        'id': 'unit-3',
        'num': 'Unit III',
        'title': 'Image Analysis and Compression',
        'color': '#7C3AED',
        'color_dark': '#A78BFA',
        'syllabus_line': 'Image Analysis and Compression: Image Segmentation, Thresholding (Global, Adaptive), Region-Based Segmentation, Morphological Operations: Erosion, Dilation, Opening, Closing, Image Features and Descriptors, SIFT, SURF, HOG, Image Compression, Lossless vs. Lossy Compression, JPEG Compression Steps and Implementation.',
        'chapters_syllabus_order': ['ch15', 'ch16', 'ch17', 'ch18', 'ch19', 'ch20', 'ch21', 'ch22', 'ch23', 'ch24']
    },
    'unit-4': {
        'id': 'unit-4',
        'num': 'Unit IV',
        'title': 'Advanced Topics in Digital Image Processing',
        'color': '#E11D48',
        'color_dark': '#FB7185',
        'syllabus_line': 'Advanced Topics in Digital Image Processing: Image Classification and Object Detection, Introduction to Convolutional Neural Networks (CNNs), Pretrained Models (VGG, ResNet, YOLO), Image Denoising using Autoencoders, Applications in Healthcare and Surveillance, Introduction to Video Processing and Motion Analysis.',
        # Note: Syllabus lists Applications in Healthcare & Surveillance before Video Processing & Motion Analysis!
        'chapters_syllabus_order': ['ch25', 'ch26', 'ch27', 'ch28', 'ch29', 'ch31', 'ch30']
    }
}

CHAPTERS_MAPPING = {
    'ch01': {
        'id': 'ch01',
        'num': 1,
        'num_str': '01',
        'file': 'chapters/ch01-big-picture.html',
        'title': 'The Big Picture: What is an Image?',
        'short_title': 'The Big Picture',
        'unit_id': 'unit-1',
        'unit_num': 'Unit I',
        'unit_title': 'Introduction to Digital Image Processing',
        'part_id': 'part-i',
        'part_name': 'Part I — The Image',
        'topic_title': 'Fundamentals of Image Processing',
        'syllabus_mention': 'Fundamentals of Image Processing: Definition of DIP, steps in digital image processing, components of an image processing system, visual perception, electromagnetic spectrum imaging.',
        'syllabus_order': 1
    },
    'ch02': {
        'id': 'ch02',
        'num': 2,
        'num_str': '02',
        'file': 'chapters/ch02-image-formation.html',
        'title': 'Image Formation & Physical Acquisition',
        'short_title': 'Formation & Acquisition',
        'unit_id': 'unit-1',
        'unit_num': 'Unit I',
        'unit_title': 'Introduction to Digital Image Processing',
        'part_id': 'part-i',
        'part_name': 'Part I — The Image',
        'topic_title': 'Image Formation',
        'syllabus_mention': 'Image Formation: Physical basis of illumination & reflectance f(x,y)=i(x,y)r(x,y), camera geometry, thin lens formula, single sensor, sensor strip, and 2D focal plane arrays.',
        'syllabus_order': 2
    },
    'ch03': {
        'id': 'ch03',
        'num': 3,
        'num_str': '03',
        'file': 'chapters/ch03-sampling-quantization.html',
        'title': 'Spatial Sampling & Quantization',
        'short_title': 'Sampling & Quantization',
        'unit_id': 'unit-1',
        'unit_num': 'Unit I',
        'unit_title': 'Introduction to Digital Image Processing',
        'part_id': 'part-i',
        'part_name': 'Part I — The Image',
        'topic_title': 'Sampling, and Quantization',
        'syllabus_mention': 'Sampling, and Quantization: 2D sampling lattice, Nyquist-Shannon sampling theorem, spatial aliasing, uniform and non-uniform quantization, bit depth k, levels L=2^k.',
        'syllabus_order': 3
    },
    'ch04': {
        'id': 'ch04',
        'num': 4,
        'num_str': '04',
        'file': 'chapters/ch04-image-representation.html',
        'title': 'Pixels, Matrices, Tensors & Resolution',
        'short_title': 'Pixels, Matrices & Resolution',
        'unit_id': 'unit-1',
        'unit_num': 'Unit I',
        'unit_title': 'Introduction to Digital Image Processing',
        'part_id': 'part-i',
        'part_name': 'Part I — The Image',
        'topic_title': 'Types of Images & Image Representation: Pixels, Bit Depth, and Resolution',
        'syllabus_mention': 'Types of Images: Grayscale, RGB, Multispectral; Image Representation: Pixels, Bit Depth, and Resolution, 4/8/m-connectivity, adjacency, distance metrics (Euclidean, D4, D8).',
        'syllabus_order': 4
    },
    'ch05': {
        'id': 'ch05',
        'num': 5,
        'num_str': '05',
        'file': 'chapters/ch05-colour-models-file-formats.html',
        'title': 'Colour Models & Image File Formats',
        'short_title': 'Colour Models & Formats',
        'unit_id': 'unit-1',
        'unit_num': 'Unit I',
        'unit_title': 'Introduction to Digital Image Processing',
        'part_id': 'part-i',
        'part_name': 'Part I — The Image',
        'topic_title': 'Color Models: RGB, HSV, CMY, YUV & File Formats: BMP, JPEG, PNG, TIFF',
        'syllabus_mention': 'Color Models: RGB, HSV, CMY, YUV; File Formats: BMP, JPEG, PNG, TIFF, CIE chromaticity, chroma subsampling (4:4:4, 4:2:2, 4:2:0), and container headers.',
        'syllabus_order': 5
    },
    'ch06': {
        'id': 'ch06',
        'num': 6,
        'num_str': '06',
        'file': 'chapters/ch06-point-processing.html',
        'title': 'Point Processing & Intensity Transformations',
        'short_title': 'Point Processing & Intensity',
        'unit_id': 'unit-2',
        'unit_num': 'Unit II',
        'unit_title': 'Image Enhancement and Restoration',
        'part_id': 'part-ii',
        'part_name': 'Part II — Improving the Image',
        'topic_title': 'Spatial Domain Techniques',
        'syllabus_mention': 'Spatial Domain Techniques: Basic gray-level transformations (image negative, log transform, power-law gamma transformations), contrast stretching, bit-plane slicing.',
        'syllabus_order': 6
    },
    'ch07': {
        'id': 'ch07',
        'num': 7,
        'num_str': '07',
        'file': 'chapters/ch07-histograms-equalization.html',
        'title': 'Histograms & Contrast Enhancement',
        'short_title': 'Histograms & Equalization',
        'unit_id': 'unit-2',
        'unit_num': 'Unit II',
        'unit_title': 'Image Enhancement and Restoration',
        'part_id': 'part-ii',
        'part_name': 'Part II — Improving the Image',
        'topic_title': 'Histogram Equalization',
        'syllabus_mention': 'Histogram Equalization: Histogram definition, normalized histogram, discrete histogram equalization derivation, histogram specification/matching, local processing, CLAHE.',
        'syllabus_order': 7
    },
    'ch08': {
        'id': 'ch08',
        'num': 8,
        'num_str': '08',
        'file': 'chapters/ch08-spatial-filtering.html',
        'title': 'Spatial Filtering & Convolution',
        'short_title': 'Spatial Filtering & Convolution',
        'unit_id': 'unit-2',
        'unit_num': 'Unit II',
        'unit_title': 'Image Enhancement and Restoration',
        'part_id': 'part-ii',
        'part_name': 'Part II — Improving the Image',
        'topic_title': 'Spatial Filtering: Mechanics & Convolution',
        'syllabus_mention': 'Spatial Filtering: Mechanics of 2D linear spatial filtering, correlation vs convolution, boundary padding (zero, clamp, reflection, wrap), separable 2D convolution.',
        'syllabus_order': 8
    },
    'ch09': {
        'id': 'ch09',
        'num': 9,
        'num_str': '09',
        'file': 'chapters/ch09-smoothing-noise-reduction.html',
        'title': 'Smoothing & Noise Reduction',
        'short_title': 'Smoothing & Noise Reduction',
        'unit_id': 'unit-2',
        'unit_num': 'Unit II',
        'unit_title': 'Image Enhancement and Restoration',
        'part_id': 'part-ii',
        'part_name': 'Part II — Improving the Image',
        'topic_title': 'Spatial Filtering: Smoothing',
        'syllabus_mention': 'Spatial Filtering: Smoothing: Box filters, weighted average, Gaussian filter derivation and parameter sigma selection, non-linear median filtering, noise reduction, bilateral smoothing.',
        'syllabus_order': 9
    },
    'ch10': {
        'id': 'ch10',
        'num': 10,
        'num_str': '10',
        'file': 'chapters/ch10-sharpening-edge-detection.html',
        'title': 'Sharpening & Edge Detection',
        'short_title': 'Sharpening & Edge Detection',
        'unit_id': 'unit-2',
        'unit_num': 'Unit II',
        'unit_title': 'Image Enhancement and Restoration',
        'part_id': 'part-ii',
        'part_name': 'Part II — Improving the Image',
        'topic_title': 'Spatial Filtering: Sharpening, Edge Detection',
        'syllabus_mention': 'Spatial Filtering: Sharpening, Edge Detection: First derivatives (Roberts, Prewitt, Sobel), second derivative (Laplacian), unsharp masking, highboost, LoG, Canny edge detector.',
        'syllabus_order': 10
    },
    'ch11': {
        'id': 'ch11',
        'num': 11,
        'num_str': '11',
        'file': 'chapters/ch11-geometric-transforms.html',
        'title': 'Geometric Transformations & Interpolation',
        'short_title': 'Geometric Transforms',
        'unit_id': 'unit-2',
        'unit_num': 'Unit II',
        'unit_title': 'Image Enhancement and Restoration',
        'part_id': 'part-ii',
        'part_name': 'Part II — Improving the Image',
        'topic_title': 'Spatial Enhancement: Geometric Transformations & Interpolation',
        'syllabus_mention': 'Spatial Domain Techniques (Geometric): Forward vs inverse mapping, affine coordinate matrices in homogeneous coordinates, nearest-neighbor, bilinear, and bicubic interpolation.',
        'syllabus_order': 11
    },
    'ch12': {
        'id': 'ch12',
        'num': 12,
        'num_str': '12',
        'file': 'chapters/ch12-fourier-transform.html',
        'title': '2D Fourier Transform & Frequency Domain',
        'short_title': 'Fourier Transform & Frequency',
        'unit_id': 'unit-2',
        'unit_num': 'Unit II',
        'unit_title': 'Image Enhancement and Restoration',
        'part_id': 'part-ii',
        'part_name': 'Part II — Improving the Image',
        'topic_title': 'Frequency Domain Techniques, Fourier Transform and Its Applications',
        'syllabus_mention': 'Frequency Domain Techniques, Fourier Transform and Its Applications: 1D and 2D Discrete Fourier Transform (DFT), Fourier magnitude & phase spectrum, centering via (-1)^(x+y), 2D Convolution Theorem, FFT.',
        'syllabus_order': 12
    },
    'ch13': {
        'id': 'ch13',
        'num': 13,
        'num_str': '13',
        'file': 'chapters/ch13-frequency-filtering.html',
        'title': 'Frequency-Domain Filtering',
        'short_title': 'Frequency-Domain Filtering',
        'unit_id': 'unit-2',
        'unit_num': 'Unit II',
        'unit_title': 'Image Enhancement and Restoration',
        'part_id': 'part-ii',
        'part_name': 'Part II — Improving the Image',
        'topic_title': 'Frequency Filters: Low-Pass, High-Pass, Band-Pass',
        'syllabus_mention': 'Frequency Filters: Low-Pass, High-Pass, Band-Pass: Ideal, Butterworth, Gaussian lowpass (ILPF, BLPF, GLPF) and highpass (IHPF, BHPF, GHPF) filters, ringing artifacts, notch filters.',
        'syllabus_order': 13
    },
    'ch14': {
        'id': 'ch14',
        'num': 14,
        'num_str': '14',
        'file': 'chapters/ch14-image-restoration.html',
        'title': 'Image Restoration & Deblurring',
        'short_title': 'Restoration & Deblurring',
        'unit_id': 'unit-2',
        'unit_num': 'Unit II',
        'unit_title': 'Image Enhancement and Restoration',
        'part_id': 'part-ii',
        'part_name': 'Part II — Improving the Image',
        'topic_title': 'Noise Reduction and Image Restoration Techniques',
        'syllabus_mention': 'Noise Reduction and Image Restoration Techniques: Image degradation model g=f*h+n, noise probability distributions, inverse filtering noise catastrophe, Wiener (MMSE) filtering, constrained least squares.',
        'syllabus_order': 14
    },
    'ch15': {
        'id': 'ch15',
        'num': 15,
        'num_str': '15',
        'file': 'chapters/ch15-segmentation-fundamentals.html',
        'title': 'Image Segmentation Fundamentals & Edge Linking',
        'short_title': 'Segmentation Fundamentals',
        'unit_id': 'unit-3',
        'unit_num': 'Unit III',
        'unit_title': 'Image Analysis and Compression',
        'part_id': 'part-iii',
        'part_name': 'Part III — Understanding Content',
        'topic_title': 'Image Segmentation',
        'syllabus_mention': 'Image Segmentation: Detection of discontinuities, point, line, and edge detection, local edge linking, global Hough transform (rho = x*cos(theta) + y*sin(theta)).',
        'syllabus_order': 15
    },
    'ch16': {
        'id': 'ch16',
        'num': 16,
        'num_str': '16',
        'file': 'chapters/ch16-thresholding-otsu.html',
        'title': 'Thresholding & Otsu\'s Method',
        'short_title': 'Thresholding & Otsu',
        'unit_id': 'unit-3',
        'unit_num': 'Unit III',
        'unit_title': 'Image Analysis and Compression',
        'part_id': 'part-iii',
        'part_name': 'Part III — Understanding Content',
        'topic_title': 'Thresholding (Global, Adaptive)',
        'syllabus_mention': 'Thresholding (Global, Adaptive): Role of illumination in thresholding, basic global thresholding, Otsu’s optimum between-class variance maximization, dual thresholding, local adaptive thresholding.',
        'syllabus_order': 16
    },
    'ch17': {
        'id': 'ch17',
        'num': 17,
        'num_str': '17',
        'file': 'chapters/ch17-region-segmentation.html',
        'title': 'Region-Based Segmentation',
        'short_title': 'Region Segmentation',
        'unit_id': 'unit-3',
        'unit_num': 'Unit III',
        'unit_title': 'Image Analysis and Compression',
        'part_id': 'part-iii',
        'part_name': 'Part III — Understanding Content',
        'topic_title': 'Region-Based Segmentation',
        'syllabus_mention': 'Region-Based Segmentation: Region growing based on seeds and similarity predicates, quadtree hierarchical region splitting and merging, watershed transform using distance transforms and markers.',
        'syllabus_order': 17
    },
    'ch18': {
        'id': 'ch18',
        'num': 18,
        'num_str': '18',
        'file': 'chapters/ch18-mathematical-morphology.html',
        'title': 'Mathematical Morphology',
        'short_title': 'Mathematical Morphology',
        'unit_id': 'unit-3',
        'unit_num': 'Unit III',
        'unit_title': 'Image Analysis and Compression',
        'part_id': 'part-iii',
        'part_name': 'Part III — Understanding Content',
        'topic_title': 'Morphological Operations: Erosion, Dilation, Opening, Closing',
        'syllabus_mention': 'Morphological Operations: Erosion, Dilation, Opening, Closing: Structuring elements, hit-or-miss transform, boundary extraction, hole filling, connected components, thinning, morphological gradient.',
        'syllabus_order': 18
    },
    'ch19': {
        'id': 'ch19',
        'num': 19,
        'num_str': '19',
        'file': 'chapters/ch19-features-descriptors.html',
        'title': 'Image Features & Descriptors',
        'short_title': 'Features & Descriptors',
        'unit_id': 'unit-3',
        'unit_num': 'Unit III',
        'unit_title': 'Image Analysis and Compression',
        'part_id': 'part-iii',
        'part_name': 'Part III — Understanding Content',
        'topic_title': 'Image Features and Descriptors',
        'syllabus_mention': 'Image Features and Descriptors: Boundary representations, Freeman chain codes, shape numbers, Fourier descriptors, regional compactness, Euler number, GLCM texture analysis, Hu’s 7 invariant moments.',
        'syllabus_order': 19
    },
    'ch20': {
        'id': 'ch20',
        'num': 20,
        'num_str': '20',
        'file': 'chapters/ch20-sift-surf-orb-hog.html',
        'title': 'Local Feature Detectors (SIFT, SURF, ORB & HOG)',
        'short_title': 'SIFT, SURF, ORB & HOG',
        'unit_id': 'unit-3',
        'unit_num': 'Unit III',
        'unit_title': 'Image Analysis and Compression',
        'part_id': 'part-iii',
        'part_name': 'Part III — Understanding Content',
        'topic_title': 'SIFT, SURF, HOG',
        'syllabus_mention': 'SIFT, SURF, HOG: Scale-space Difference of Gaussians (DoG), keypoint localization, SIFT 128-D descriptor, SURF integral box filters, FAST/ORB binary descriptors, Histogram of Oriented Gradients (HOG).',
        'syllabus_order': 20
    },
    'ch21': {
        'id': 'ch21',
        'num': 21,
        'num_str': '21',
        'file': 'chapters/ch21-compression-entropy.html',
        'title': 'Image Compression Fundamentals',
        'short_title': 'Compression & Entropy',
        'unit_id': 'unit-3',
        'unit_num': 'Unit III',
        'unit_title': 'Image Analysis and Compression',
        'part_id': 'part-iv',
        'part_name': 'Part IV — Compressing Images',
        'topic_title': 'Image Compression',
        'syllabus_mention': 'Image Compression: Coding redundancy, spatial / interpixel redundancy, psychovisual redundancy, compression ratio, Shannon information entropy, noiseless coding theorem, fidelity criteria (MSE, PSNR).',
        'syllabus_order': 21
    },
    'ch22': {
        'id': 'ch22',
        'num': 22,
        'num_str': '22',
        'file': 'chapters/ch22-lossless-coding.html',
        'title': 'Entropy, Run-Length Encoding & Huffman Coding',
        'short_title': 'Lossless: RLE & Huffman',
        'unit_id': 'unit-3',
        'unit_num': 'Unit III',
        'unit_title': 'Image Analysis and Compression',
        'part_id': 'part-iv',
        'part_name': 'Part IV — Compressing Images',
        'topic_title': 'Lossless vs. Lossy Compression',
        'syllabus_mention': 'Lossless vs. Lossy Compression: Run-Length Encoding (RLE) for binary and grayscale, bit-plane compression, Huffman optimal prefix-free code trees, average codeword length, coding efficiency, LZW dictionary coding.',
        'syllabus_order': 22
    },
    'ch23': {
        'id': 'ch23',
        'num': 23,
        'num_str': '23',
        'file': 'chapters/ch23-lossy-dct-jpeg.html',
        'title': 'Transform Coding & Discrete Cosine Transform',
        'short_title': 'Lossy: DCT & JPEG',
        'unit_id': 'unit-3',
        'unit_num': 'Unit III',
        'unit_title': 'Image Analysis and Compression',
        'part_id': 'part-iv',
        'part_name': 'Part IV — Compressing Images',
        'topic_title': 'JPEG Compression Steps and Implementation (Transform & DCT)',
        'syllabus_mention': 'JPEG Compression Steps and Implementation: 2D Discrete Cosine Transform (DCT-II), energy compaction, sub-image 8x8 block decomposition, psychoacoustic quantization matrices, zigzag scan ordering.',
        'syllabus_order': 23
    },
    'ch24': {
        'id': 'ch24',
        'num': 24,
        'num_str': '24',
        'file': 'chapters/ch24-wavelets-jpeg2000.html',
        'title': 'JPEG Compression End to End & JPEG 2000',
        'short_title': 'Wavelets & JPEG 2000',
        'unit_id': 'unit-3',
        'unit_num': 'Unit III',
        'unit_title': 'Image Analysis and Compression',
        'part_id': 'part-iv',
        'part_name': 'Part IV — Compressing Images',
        'topic_title': 'JPEG Compression Steps and Implementation (Pipeline & Standards)',
        'syllabus_mention': 'JPEG Compression Steps and Implementation: End-to-end baseline sequential JPEG pipeline, DC DPCM differential coding, AC zero-run Huffman coding, JPEG 2000 Discrete Wavelet Transform (DWT) comparison.',
        'syllabus_order': 24
    },
    'ch25': {
        'id': 'ch25',
        'num': 25,
        'num_str': '25',
        'file': 'chapters/ch25-image-classification.html',
        'title': 'Image Classification Foundations',
        'short_title': 'Image Classification',
        'unit_id': 'unit-4',
        'unit_num': 'Unit IV',
        'unit_title': 'Advanced Topics in Digital Image Processing',
        'part_id': 'part-v',
        'part_name': 'Part V — Intelligent Vision',
        'topic_title': 'Image Classification and Object Detection (Part 1: Classification)',
        'syllabus_mention': 'Image Classification and Object Detection: Feature space decision boundaries, minimum distance classifier, k-Nearest Neighbors (k-NN), linear classifier formulation (Wx + b), Softmax cross-entropy loss.',
        'syllabus_order': 25
    },
    'ch26': {
        'id': 'ch26',
        'num': 26,
        'num_str': '26',
        'file': 'chapters/ch26-cnns-image-processing.html',
        'title': 'Convolutional Neural Networks for Image Processing',
        'short_title': 'CNNs for Vision',
        'unit_id': 'unit-4',
        'unit_num': 'Unit IV',
        'unit_title': 'Advanced Topics in Digital Image Processing',
        'part_id': 'part-v',
        'part_name': 'Part V — Intelligent Vision',
        'topic_title': 'Introduction to Convolutional Neural Networks (CNNs)',
        'syllabus_mention': 'Introduction to Convolutional Neural Networks (CNNs): Connection between spatial domain filtering and CNNs, 2D convolution layers, parameter sharing, receptive fields, stride & padding, ReLU, pooling layers.',
        'syllabus_order': 26
    },
    'ch27': {
        'id': 'ch27',
        'num': 27,
        'num_str': '27',
        'file': 'chapters/ch27-modern-vision-architectures.html',
        'title': 'Modern Vision Architectures: VGG & ResNet',
        'short_title': 'VGG & ResNet',
        'unit_id': 'unit-4',
        'unit_num': 'Unit IV',
        'unit_title': 'Advanced Topics in Digital Image Processing',
        'part_id': 'part-v',
        'part_name': 'Part V — Intelligent Vision',
        'topic_title': 'Pretrained Models (VGG, ResNet)',
        'syllabus_mention': 'Pretrained Models (VGG, ResNet): VGGNet 3x3 filter factorization, vanishing gradient problem, ResNet residual learning framework, identity skip connections (H(x) = F(x) + x), transfer learning.',
        'syllabus_order': 27
    },
    'ch28': {
        'id': 'ch28',
        'num': 28,
        'num_str': '28',
        'file': 'chapters/ch28-object-detection-yolo.html',
        'title': 'Object Detection & YOLO',
        'short_title': 'Object Detection: YOLO',
        'unit_id': 'unit-4',
        'unit_num': 'Unit IV',
        'unit_title': 'Advanced Topics in Digital Image Processing',
        'part_id': 'part-v',
        'part_name': 'Part V — Intelligent Vision',
        'topic_title': 'Pretrained Models (YOLO) & Object Detection',
        'syllabus_mention': 'Image Classification and Object Detection & Pretrained Models (YOLO): Localization vs detection, bounding box representation [x,y,w,h], IoU, Non-Maximum Suppression (NMS), YOLO unified grid regression.',
        'syllabus_order': 28
    },
    'ch29': {
        'id': 'ch29',
        'num': 29,
        'num_str': '29',
        'file': 'chapters/ch29-image-denoising-autoencoders.html',
        'title': 'Image Denoising with Autoencoders',
        'short_title': 'Autoencoders Denoising',
        'unit_id': 'unit-4',
        'unit_num': 'Unit IV',
        'unit_title': 'Advanced Topics in Digital Image Processing',
        'part_id': 'part-v',
        'part_name': 'Part V — Intelligent Vision',
        'topic_title': 'Image Denoising using Autoencoders',
        'syllabus_mention': 'Image Denoising using Autoencoders: Unsupervised visual representation, encoder-decoder bottleneck, Convolutional Autoencoder (CAE), transpose convolutions, reconstruction loss, spatial filtering comparison.',
        'syllabus_order': 29
    },
    'ch31': {
        'id': 'ch31',
        'num': 31,
        'num_str': '31',
        'file': 'chapters/ch31-dip-applications-engineering.html',
        'title': 'DIP Applications, Engineering Context & Responsible Use',
        'short_title': 'Applications & Ethics',
        'unit_id': 'unit-4',
        'unit_num': 'Unit IV',
        'unit_title': 'Advanced Topics in Digital Image Processing',
        'part_id': 'part-v',
        'part_name': 'Part V — Intelligent Vision',
        'topic_title': 'Applications in Healthcare and Surveillance',
        'syllabus_mention': 'Applications in Healthcare and Surveillance: Medical imaging (CT Hounsfield units, MRI artifact removal, automated tumor segmentation), surveillance monitoring, biometrics, ethics & responsible vision AI.',
        'syllabus_order': 30  # In uploaded syllabus, Healthcare & Surveillance appears before Video Processing!
    },
    'ch30': {
        'id': 'ch30',
        'num': 30,
        'num_str': '30',
        'file': 'chapters/ch30-video-motion-analysis.html',
        'title': 'Video Processing & Motion Analysis',
        'short_title': 'Video & Motion Analysis',
        'unit_id': 'unit-4',
        'unit_num': 'Unit IV',
        'unit_title': 'Advanced Topics in Digital Image Processing',
        'part_id': 'part-v',
        'part_name': 'Part V — Intelligent Vision',
        'topic_title': 'Introduction to Video Processing and Motion Analysis',
        'syllabus_mention': 'Introduction to Video Processing and Motion Analysis: Video as 3D spatiotemporal volume I(x,y,t), frame differencing, background subtraction (MOG2), optical flow constraint equation, Lucas-Kanade tracking.',
        'syllabus_order': 31  # In uploaded syllabus, Video Processing is listed after Applications!
    }
}
